name: stat-comp
channels:
        - conda-forge
dependencies:
        - python=3.6
        - numpy
        - scipy
        - pandas
        - xarray=0.16.0
        - fsspec=0.8.0
        - dask 
        - dask-jobqueue
        - distributed
        - netcdf4
        - bokeh
        - cartopy
        - cmocean
        - ipykernel
        - matplotlib
        - papermill
        - seawater
        - seaborn
        - erddapy=0.6
        - pip
        - pip:
                - git+http://github.com/xgcm/euroargodev/argopy.git@master
                - erddapy=0.6.0

